# Generated by Django 2.2 on 2019-08-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_comment',
            fields=[
                ('detail', models.TextField(default='[]', verbose_name='个人评论内容')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '个人参与任务详情',
                'verbose_name_plural': '个人参与任务详情',
            },
        ),
        migrations.CreateModel(
            name='personal_progress',
            fields=[
                ('detail', models.TextField(verbose_name='个人进度内容')),
                ('id', models.CharField(default='[]', max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '个人进度',
                'verbose_name_plural': '个人进度',
                'permissions': {('edit_personal_progress', '编辑个人进度')},
            },
        ),
        migrations.CreateModel(
            name='personal_schedule',
            fields=[
                ('detail', models.TextField(default='[]', verbose_name='个人时间表内容')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '个人时间表',
                'verbose_name_plural': '个人时间表',
                'permissions': {('edit_personal_schedule', '编辑个人时间表')},
            },
        ),
        migrations.CreateModel(
            name='personal_scheduleAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
