# Generated by Django 2.2 on 2019-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_comment',
            name='detail',
            field=models.TextField(default='[]', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='personal_progress',
            name='id',
            field=models.CharField(default='[]', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personal_shedule',
            name='detail',
            field=models.TextField(default='[]', verbose_name='内容'),
        ),
    ]
