# Generated by Django 2.2 on 2019-04-21 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student_id', models.CharField(max_length=10)),
                ('cloud_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('magor', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=5)),
                ('room', models.CharField(max_length=5)),
                ('home_address', models.CharField(max_length=20)),
                ('guardian_phone', models.CharField(max_length=12)),
                ('introduction', models.CharField(max_length=350)),
                ('involved_projects', models.CharField(max_length=100)),
                ('read_notifications', models.TextField()),
                ('unread_notifications', models.TextField()),
                ('sex', models.NullBooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
