# Generated by Django 2.2 on 2019-05-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('common_user', '普通学生'),)},
        ),
    ]
