# Generated by Django 2.2 on 2019-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(default=None, max_length=10, verbose_name='生日'),
            preserve_default=False,
        ),
    ]
