# Generated by Django 2.2 on 2019-06-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='involved_projects',
            field=models.TextField(default='[]'),
        ),
    ]
