# Generated by Django 2.2 on 2019-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='management_projects',
            new_name='managed_projects',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='managed_projects_number',
            field=models.IntegerField(default=0),
        ),
    ]
