# Generated by Django 2.2 on 2019-07-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190708_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='magor',
            new_name='major',
        ),
    ]
