# Generated by Django 2.2 on 2019-04-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190421_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cloud_id',
            field=models.CharField(max_length=20, verbose_name='云顶号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(max_length=4, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='guardian_phone',
            field=models.CharField(max_length=11, verbose_name='家长手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_address',
            field=models.CharField(max_length=100, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(max_length=350, verbose_name='个人介绍'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='magor',
            field=models.CharField(max_length=10, verbose_name='方向'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=5, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.CharField(max_length=8, verbose_name='宿舍号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default=1, max_length=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(max_length=11, verbose_name='学号'),
        ),
    ]
