# Generated by Django 2.2 on 2019-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190622_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='management_projects',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='read_notifications',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unread_notifications',
            field=models.TextField(default='[]'),
        ),
    ]
