# Generated by Django 2.2 on 2019-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190423_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='management_projects',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='magor',
            field=models.CharField(choices=[('M', '机电创新团队'), ('P', 'Python'), ('N', 'Node.js'), ('J', 'Java'), ('F', '前端'), ('D', '设计')], max_length=1, verbose_name='方向'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1, verbose_name='性别'),
        ),
    ]
