# Generated by Django 2.2 on 2019-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190708_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='guardian_phone',
            field=models.CharField(default='', max_length=11, verbose_name='家长手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_address',
            field=models.CharField(default='', max_length=100, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.CharField(default='', max_length=350, verbose_name='个人介绍'),
        ),
    ]
