# Generated by Django 2.2 on 2019-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20, verbose_name='任务名')),
                ('publish_data', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(verbose_name='结束时间')),
                ('task_status', models.IntegerField(choices=[(0, '已挂起'), (-1, '已结束'), (1, '进行中')], verbose_name='任务状态')),
                ('member', models.CharField(max_length=200, verbose_name='成员')),
                ('all_members', models.CharField(max_length=200, verbose_name='参加过项目的成员')),
                ('task_description', models.CharField(max_length=200, verbose_name='任务描述')),
                ('task_need', models.CharField(max_length=1000, verbose_name='任务需求')),
                ('task_schedule', models.CharField(max_length=1000, verbose_name='时间安排')),
                ('appendixes', models.CharField(max_length=200, verbose_name='附件')),
                ('task_progress', models.TextField(verbose_name='任务进度')),
            ],
            options={
                'permissions': {('glance_over_task_details', '浏览任务详情'), ('edit_tasks', '编辑任务'), ('create_tasks', '新建任务')},
            },
        ),
    ]
