# Generated by Django 2.2 on 2019-06-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='member',
            new_name='members',
        ),
    ]
