# Generated by Django 2.2 on 2019-06-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190616_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_data', models.DateField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('creator', models.IntegerField(verbose_name='评论人')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'permissions': {('edit_comments', '编辑任务'), ('view_comments', '查看任务')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.IntegerField(default=None, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='leader',
            field=models.CharField(default=None, max_length=20, verbose_name='组长'),
            preserve_default=False,
        ),
    ]
