# Generated by Django 2.2 on 2019-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190628_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': {('view_personal_shedule', '查看个人时间表'), ('edit_personal_comments', '编辑个人评价'), ('view_personal_progress', '查看个人进度'), ('glance_over_task_details', '浏览任务详情'), ('edit_progress', '编辑任务时间表'), ('create_tasks', '新建任务'), ('edit_tasks', '编辑任务'), ('edit_shedule', '编辑任务进度'), ('delete_appendix', '删除附件'), ('view_personal_comments', '查看个人评价'), ('edit_appendix', '编辑附件')}},
        ),
        migrations.AddField(
            model_name='task',
            name='task_comment',
            field=models.TextField(default='[]', verbose_name='任务评价'),
        ),
        migrations.AlterField(
            model_name='task',
            name='all_members',
            field=models.CharField(default='[]', max_length=200, verbose_name='参加过项目的成员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='appendixes',
            field=models.CharField(default='[]', max_length=200, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='task',
            name='leaders',
            field=models.CharField(default='[]', max_length=20, verbose_name='组长'),
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.CharField(default='[]', max_length=200, verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='', max_length=200, verbose_name='任务描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_need',
            field=models.CharField(default='', max_length=1000, verbose_name='任务需求'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_progress',
            field=models.TextField(default='[]', verbose_name='任务进度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_schedule',
            field=models.TextField(default='{"publish_date": "", "upgrade_date": "", "content": "", "creater": ""}', verbose_name='时间安排'),
        ),
    ]
