# Generated by Django 2.2 on 2019-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190730_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_schedule',
            field=models.TextField(default='[]', verbose_name='时间安排'),
        ),
    ]
