# Generated by Django 2.2 on 2019-08-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noti',
        ),
    ]
