# Generated by Django 2.2 on 2019-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='sender',
            field=models.CharField(choices=[('0', '管理员'), ('1', '副组长'), ('2', '系统')], max_length=1, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='noti',
            name='type',
            field=models.CharField(choices=[('0', '全站消息'), ('1', '组内消息'), ('2', '个人消息')], default='2', max_length=1, verbose_name='消息类型'),
        ),
    ]
