# Generated by Django 2.2 on 2019-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('upload_date', models.DateField(verbose_name='上传日期')),
                ('task_id', models.IntegerField()),
                ('publisher', models.IntegerField()),
            ],
            options={
                'permissions': {('edit_appendix', '编辑附件')},
            },
        ),
    ]
