# Generated by Django 2.2 on 2019-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='filesize',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
