# Generated by Django 2.2 on 2019-08-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20190826_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appendix',
            old_name='filename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appendix',
            old_name='filesize',
            new_name='size',
        ),
    ]
